name: ubuntu1604-miniconda-build

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    
    - name: Install miniconda
      run: |
        sudo wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O ~/miniconda.sh && \
          sudo /bin/bash ~/miniconda.sh -b -p /opt/conda
          sudo rm ~/miniconda.sh
          sudo /opt/conda/bin/conda clean -tipsy
          sudo ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh
          sudo echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc
        source /opt/conda/etc/profile.d/conda.sh
        conda activate
        TINI_VERSION=v0.16.1
        sudo wget --quiet https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -O /usr/bin/tini && sudo chmod +x /usr/bin/tini
        conda config --set always_yes yes
    - name: Install dependencies
      run: |
        sed -i -E 's/(python=)(.*)/\1'${{ matrix.python-version }}'/' ./environment.yml  # update python version in environment.yml
        source /opt/conda/etc/profile.d/conda.sh
        sudo conda env create -p /opt/conda/envs/solaris -f environment.yml
        conda list -n solaris
        conda activate solaris
        python --version
    - name: Install solaris and test with pytest
      run: |
        source /opt/conda/etc/profile.d/conda.sh
        sudo conda activate solaris
        sudo pip install -q -e .[test]
        sudo conda install pytest=4.6.2 -c conda-forge
        sudo pip install codecov pytest-cov
        sudo python -m pytest --cov=./ && codecov
